/* automatically generated by configure */
/* on Tue Jul 25 10:34:15 GMTDT 2006 */
/* target uppercase defines */
 
#ifndef TARGET_OS_WINDOWS
#define TARGET_OS_WINDOWS "windows"
#endif
 
#ifndef TARGET_OS_TYPE
#define TARGET_OS_TYPE "windows"
#endif
 
#ifndef TARGET_CPU_I686
#define TARGET_CPU_I686 "i686"
#endif
 
#ifndef TARGET_CPU_I
#define TARGET_CPU_I "i686"
#endif
 
#ifndef TARGET_CPU_TYPE
#define TARGET_CPU_TYPE "i686"
#endif
 
#ifndef TARGET_ARCH_I386
#define TARGET_ARCH_I386 "i386"
#endif
 
#ifndef TARGET_ARCH_TYPE
#define TARGET_ARCH_TYPE "i386"
#endif
/* host uppercase defines */
 
#ifndef HOST_OS_WINDOWS
#define HOST_OS_WINDOWS "windows"
#endif
 
#ifndef HOST_OS_TYPE
#define HOST_OS_TYPE "cygwin"
#endif
 
#ifndef HOST_CPU_I686
#define HOST_CPU_I686 "i686"
#endif
 
#ifndef HOST_CPU_I
#define HOST_CPU_I "i686"
#endif
 
#ifndef HOST_CPU_TYPE
#define HOST_CPU_TYPE "i686"
#endif
 
#ifndef HOST_ARCH_I386
#define HOST_ARCH_I386 "i386"
#endif
 
#ifndef HOST_ARCH_TYPE
#define HOST_ARCH_TYPE "i386"
#endif
