FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    gcc make automake autoconf m4 pkg-config libtool flex bison valgrind \
    check libbz2-dev libcurl4-openssl-dev libjson-c-dev libmilter-dev \
    libncurses5-dev libpcre2-dev libssl-dev libxml2-dev zlib1g-dev
