[package]
name = "open_alz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
cursor = "2.3.0"
deflate = "1.0.0"
flate2 = "1.0.28"

[workspace]
