/* TODO: include GPL headers */
#include <hashtab.h>
static struct element entities_htable_elements[] = {
	{(const unsigned char*)"varpropto", 8733},
	{(const unsigned char*)"ncong", 8775},
	{(const unsigned char*)"grave", 96},
	{NULL, 0},
	{(const unsigned char*)"toea", 10536},
	{(const unsigned char*)"map", 8614},
	{(const unsigned char*)"nap", 8777},
	{(const unsigned char*)"lap", 10885},
	{NULL, 0},
	{(const unsigned char*)"gap", 10886},
	{NULL, 0},
	{(const unsigned char*)"twoheadrightarrow", 8608},
	{NULL, 0},
	{(const unsigned char*)"Ll", 8920},
	{(const unsigned char*)"amalg", 10815},
	{(const unsigned char*)"geqslant", 10878},
	{NULL, 0},
	{(const unsigned char*)"origof", 8886},
	{(const unsigned char*)"Tab", 9},
	{NULL, 0},
	{(const unsigned char*)"leqslant", 10877},
	{(const unsigned char*)"asympeq", 8781},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"sext", 10038},
	{(const unsigned char*)"Wedge", 8896},
	{(const unsigned char*)"sqcap", 8851},
	{(const unsigned char*)"loang", 12312},
	{(const unsigned char*)"ngeq", 8817},
	{NULL, 0},
	{(const unsigned char*)"NotLessTilde", 8820},
	{(const unsigned char*)"nwArr", 8662},
	{NULL, 0},
	{(const unsigned char*)"roang", 12313},
	{(const unsigned char*)"Delta", 916},
	{NULL, 0},
	{(const unsigned char*)"swArr", 8665},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"DifferentialD", 8518},
	{(const unsigned char*)"gl", 8823},
	{(const unsigned char*)"loz", 9674},
	{(const unsigned char*)"Prime", 8243},
	{(const unsigned char*)"ShortRightArrow", 8594},
	{(const unsigned char*)"sigmaf", 962},
	{(const unsigned char*)"ll", 8810},
	{(const unsigned char*)"rx", 8478},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"circledS", 9416},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"notni", 8716},
	{NULL, 0},
	{(const unsigned char*)"wedge", 8743},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"rightrightarrows", 8649},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"delta", 948},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"ffllig", 64260},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Bernoullis", 8492},
	{(const unsigned char*)"djcy", 1106},
	{NULL, 0},
	{(const unsigned char*)"gjcy", 1107},
	{(const unsigned char*)"prime", 8242},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"kjcy", 1116},
	{(const unsigned char*)"ljcy", 1113},
	{(const unsigned char*)"lmoustache", 9136},
	{(const unsigned char*)"njcy", 1114},
	{(const unsigned char*)"boxDl", 9558},
	{(const unsigned char*)"clubs", 9827},
	{(const unsigned char*)"Integral", 8747},
	{NULL, 0},
	{(const unsigned char*)"rmoustache", 9137},
	{(const unsigned char*)"sol", 47},
	{(const unsigned char*)"SquareSubset", 8847},
	{NULL, 0},
	{(const unsigned char*)"rect", 9645},
	{(const unsigned char*)"sect", 167},
	{(const unsigned char*)"VeryThinSpace", 8202},
	{(const unsigned char*)"lesssim", 8818},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"UnderBrace", 65080},
	{NULL, 0},
	{(const unsigned char*)"comp", 8705},
	{(const unsigned char*)"mapstoup", 8613},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"circ", 710},
	{(const unsigned char*)"complement", 8705},
	{(const unsigned char*)"flat", 9837},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"LowerLeftArrow", 8601},
	{NULL, 0},
	{(const unsigned char*)"cuesc", 8927},
	{(const unsigned char*)"sce", 10928},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"euro", 8364},
	{(const unsigned char*)"succcurlyeq", 8829},
	{(const unsigned char*)"LeftCeiling", 8968},
	{(const unsigned char*)"vprop", 8733},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"nexists", 8708},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"pitchfork", 8916},
	{(const unsigned char*)"darr2", 8650},
	{NULL, 0},
	{(const unsigned char*)"Ubrcy", 1038},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"sqsupe", 8850},
	{(const unsigned char*)"eparsl", 10723},
	{NULL, 0},
	{(const unsigned char*)"larr2", 8647},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"LeftUpVectorBar", 10584},
	{(const unsigned char*)"sqsupseteq", 8850},
	{NULL, 0},
	{(const unsigned char*)"rarr2", 8649},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"uarr2", 8648},
	{(const unsigned char*)"veeeq", 8794},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"AElig", 198},
	{(const unsigned char*)"notnivb", 8958},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"plusb", 8862},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"DoubleRightTee", 8872},
	{(const unsigned char*)"NotSquareSupersetEqual", 8931},
	{(const unsigned char*)"hookrightarrow", 8618},
	{(const unsigned char*)"ubrcy", 1118},
	{NULL, 0},
	{(const unsigned char*)"OElig", 338},
	{NULL, 0},
	{(const unsigned char*)"NotGreaterTilde", 8821},
	{(const unsigned char*)"filig", 64257},
	{(const unsigned char*)"nlt", 8814},
	{(const unsigned char*)"Agr", 913},
	{(const unsigned char*)"GreaterEqual", 8805},
	{(const unsigned char*)"mldr", 8230},
	{(const unsigned char*)"nldr", 8229},
	{(const unsigned char*)"drcrop", 8972},
	{(const unsigned char*)"Dgr", 916},
	{(const unsigned char*)"Bgr", 914},
	{(const unsigned char*)"Igr", 921},
	{(const unsigned char*)"angmsd", 8737},
	{(const unsigned char*)"trie", 8796},
	{(const unsigned char*)"Kgr", 922},
	{(const unsigned char*)"Ggr", 915},
	{(const unsigned char*)"Mgr", 924},
	{(const unsigned char*)"Egr", 917},
	{(const unsigned char*)"Ogr", 927},
	{(const unsigned char*)"Ngr", 925},
	{(const unsigned char*)"Lgr", 923},
	{(const unsigned char*)"Pgr", 928},
	{(const unsigned char*)"Sgr", 931},
	{(const unsigned char*)"cong", 8773},
	{(const unsigned char*)"doteqdot", 8785},
	{(const unsigned char*)"urcrop", 8974},
	{(const unsigned char*)"Rgr", 929},
	{(const unsigned char*)"Xgr", 926},
	{(const unsigned char*)"Tgr", 932},
	{(const unsigned char*)"Ugr", 933},
	{NULL, 0},
	{(const unsigned char*)"nless", 8814},
	{(const unsigned char*)"LeftTee", 8867},
	{(const unsigned char*)"OverBar", 175},
	{(const unsigned char*)"Zgr", 918},
	{(const unsigned char*)"agr", 945},
	{(const unsigned char*)"bgr", 946},
	{(const unsigned char*)"phis", 981},
	{(const unsigned char*)"dgr", 948},
	{(const unsigned char*)"intlarhk", 10775},
	{(const unsigned char*)"boxplus", 8862},
	{(const unsigned char*)"ggr", 947},
	{(const unsigned char*)"egr", 949},
	{(const unsigned char*)"nrtrie", 8941},
	{(const unsigned char*)"rdldhar", 10601},
	{(const unsigned char*)"lrcorner", 8991},
	{(const unsigned char*)"igr", 953},
	{(const unsigned char*)"lgr", 955},
	{(const unsigned char*)"lhblk", 9604},
	{(const unsigned char*)"ngr", 957},
	{(const unsigned char*)"mgr", 956},
	{(const unsigned char*)"kgr", 954},
	{(const unsigned char*)"ogr", 959},
	{(const unsigned char*)"urcorner", 8989},
	{(const unsigned char*)"sgr", 963},
	{(const unsigned char*)"boxUL", 9565},
	{(const unsigned char*)"npolint", 10772},
	{(const unsigned char*)"uhblk", 9600},
	{(const unsigned char*)"rgr", 961},
	{(const unsigned char*)"curarrm", 10556},
	{(const unsigned char*)"pgr", 960},
	{(const unsigned char*)"ruluhar", 10600},
	{(const unsigned char*)"lbbrk", 12308},
	{(const unsigned char*)"zgr", 950},
	{(const unsigned char*)"tgr", 964},
	{(const unsigned char*)"ugr", 965},
	{NULL, 0},
	{(const unsigned char*)"rbbrk", 12309},
	{(const unsigned char*)"profline", 8978},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"rlm", 8207},
	{(const unsigned char*)"OverBrace", 65079},
	{(const unsigned char*)"xgr", 958},
	{(const unsigned char*)"lsaquo", 8249},
	{NULL, 0},
	{(const unsigned char*)"nwarrow", 8598},
	{(const unsigned char*)"Equilibrium", 8652},
	{NULL, 0},
	{(const unsigned char*)"rsaquo", 8250},
	{NULL, 0},
	{(const unsigned char*)"swarrow", 8601},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"prec", 8826},
	{(const unsigned char*)"ltrie", 8884},
	{(const unsigned char*)"dharl", 8643},
	{(const unsigned char*)"shortmid", 8739},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"nleftrightarrow", 8622},
	{(const unsigned char*)"rtrie", 8885},
	{(const unsigned char*)"Im", 8465},
	{(const unsigned char*)"frown", 8994},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"pertenk", 8241},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"lessgtr", 8822},
	{(const unsigned char*)"bigvee", 8897},
	{(const unsigned char*)"supseteq", 8839},
	{(const unsigned char*)"uharl", 8639},
	{NULL, 0},
	{(const unsigned char*)"Longrightarrow", 10233},
	{(const unsigned char*)"lrarr2", 8646},
	{NULL, 0},
	{(const unsigned char*)"wreath", 8768},
	{NULL, 0},
	{(const unsigned char*)"Updownarrow", 8661},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"lessdot", 8918},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"nlArr", 8653},
	{(const unsigned char*)"SOFTcy", 1068},
	{NULL, 0},
	{(const unsigned char*)"Barwed", 8966},
	{(const unsigned char*)"upharpoonleft", 8639},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"FilledVerySmallSquare", 9642},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"coprod", 8720},
	{(const unsigned char*)"pm", 177},
	{NULL, 0},
	{(const unsigned char*)"nLeftarrow", 8653},
	{NULL, 0},
	{(const unsigned char*)"DScy", 1029},
	{(const unsigned char*)"xlArr", 10232},
	{(const unsigned char*)"longrightarrow", 10230},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"subseteq", 8838},
	{NULL, 0},
	{(const unsigned char*)"updownarrow", 8597},
	{(const unsigned char*)"bsime", 8909},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"supsetneq", 8843},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"frac56", 8538},
	{NULL, 0},
	{(const unsigned char*)"TScy", 1062},
	{NULL, 0},
	{(const unsigned char*)"zeetrf", 8488},
	{(const unsigned char*)"ogon", 731},
	{(const unsigned char*)"barwed", 8965},
	{(const unsigned char*)"nsime", 8772},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"lEg", 10891},
	{(const unsigned char*)"lrhar", 8651},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"boxminus", 8863},
	{(const unsigned char*)"ape", 8778},
	{NULL, 0},
	{(const unsigned char*)"divonx", 8903},
	{(const unsigned char*)"hksearow", 10533},
	{(const unsigned char*)"boxhD", 9573},
	{(const unsigned char*)"NotLessEqual", 8816},
	{(const unsigned char*)"ang90", 8735},
	{(const unsigned char*)"sstarf", 8902},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"subsetneq", 8842},
	{(const unsigned char*)"Darr", 8609},
	{NULL, 0},
	{(const unsigned char*)"curarr", 8631},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"real", 8476},
	{(const unsigned char*)"Larr", 8606},
	{(const unsigned char*)"CircleDot", 8857},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"CircleTimes", 8855},
	{(const unsigned char*)"Rarr", 8608},
	{(const unsigned char*)"varpi", 982},
	{(const unsigned char*)"SuchThat", 8715},
	{(const unsigned char*)"Uarr", 8607},
	{(const unsigned char*)"smeparsl", 10724},
	{NULL, 0},
	{(const unsigned char*)"orslope", 10839},
	{(const unsigned char*)"cuwed", 8911},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Breve", 728},
	{(const unsigned char*)"nwarr", 8598},
	{NULL, 0},
	{(const unsigned char*)"orv", 10843},
	{(const unsigned char*)"zwj", 8205},
	{(const unsigned char*)"swarr", 8601},
	{NULL, 0},
	{(const unsigned char*)"darr", 8595},
	{(const unsigned char*)"gtrdot", 8919},
	{(const unsigned char*)"precneqq", 10933},
	{(const unsigned char*)"LessGreater", 8822},
	{(const unsigned char*)"harr", 8596},
	{(const unsigned char*)"UpperLeftArrow", 8598},
	{(const unsigned char*)"Verbar", 8214},
	{(const unsigned char*)"harrw", 8621},
	{(const unsigned char*)"TildeTilde", 8776},
	{(const unsigned char*)"larr", 8592},
	{NULL, 0},
	{(const unsigned char*)"succsim", 8831},
	{(const unsigned char*)"rarrw", 8605},
	{NULL, 0},
	{(const unsigned char*)"rarr", 8594},
	{(const unsigned char*)"prnE", 10933},
	{(const unsigned char*)"Hat", 94},
	{(const unsigned char*)"uarr", 8593},
	{(const unsigned char*)"varr", 8597},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"boxvR", 9566},
	{NULL, 0},
	{(const unsigned char*)"micro", 181},
	{(const unsigned char*)"breve", 728},
	{NULL, 0},
	{(const unsigned char*)"nequiv", 8802},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"verbar", 124},
	{(const unsigned char*)"lopar", 10629},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"frac35", 8535},
	{(const unsigned char*)"RightArrow", 8594},
	{(const unsigned char*)"copy", 169},
	{(const unsigned char*)"ropar", 10630},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"nsubseteq", 8840},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"nvlArr", 10498},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"setminus", 8726},
	{(const unsigned char*)"boxvH", 9578},
	{(const unsigned char*)"doteq", 8784},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"vartriangleleft", 8882},
	{NULL, 0},
	{(const unsigned char*)"RightTriangleBar", 10704},
	{(const unsigned char*)"shy", 173},
	{(const unsigned char*)"RightUpVectorBar", 10580},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Kappa", 922},
	{NULL, 0},
	{(const unsigned char*)"leftrightarrows", 8646},
	{(const unsigned char*)"sqsupset", 8848},
	{(const unsigned char*)"rationals", 8474},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"cent", 162},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"lobrk", 12314},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"OverBracket", 9140},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"robrk", 12315},
	{(const unsigned char*)"Fouriertrf", 8497},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"blacktriangleleft", 9666},
	{(const unsigned char*)"bumpe", 8783},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"kappa", 954},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"weierp", 8472},
	{NULL, 0},
	{(const unsigned char*)"intcal", 8890},
	{(const unsigned char*)"rarrc", 10547},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"iiint", 8749},
	{NULL, 0},
	{(const unsigned char*)"boxdr", 9484},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"percnt", 37},
	{(const unsigned char*)"top", 8868},
	{NULL, 0},
	{(const unsigned char*)"ffilig", 64259},
	{(const unsigned char*)"notnivc", 8957},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"diams", 9830},
	{NULL, 0},
	{(const unsigned char*)"maltese", 10016},
	{(const unsigned char*)"vartriangleright", 8883},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"OverParenthesis", 65077},
	{(const unsigned char*)"nesear", 10536},
	{(const unsigned char*)"LessFullEqual", 8806},
	{NULL, 0},
	{(const unsigned char*)"UpDownArrow", 8597},
	{(const unsigned char*)"measuredangle", 8737},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Leftarrow", 8656},
	{(const unsigned char*)"HumpDownHump", 8782},
	{(const unsigned char*)"frac14", 188},
	{NULL, 0},
	{(const unsigned char*)"LeftUpVector", 8639},
	{(const unsigned char*)"bigotimes", 10754},
	{(const unsigned char*)"questeq", 8799},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"GreaterFullEqual", 8807},
	{NULL, 0},
	{(const unsigned char*)"in", 8712},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Del", 8711},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"CHcy", 1063},
	{(const unsigned char*)"supne", 8843},
	{NULL, 0},
	{(const unsigned char*)"leftarrow", 8592},
	{(const unsigned char*)"ges", 10878},
	{(const unsigned char*)"bnot", 8976},
	{(const unsigned char*)"mumap", 8888},
	{(const unsigned char*)"LeftTriangleEqual", 8884},
	{(const unsigned char*)"KHcy", 1061},
	{(const unsigned char*)"les", 10877},
	{(const unsigned char*)"xutri", 9651},
	{NULL, 0},
	{(const unsigned char*)"caron", 711},
	{NULL, 0},
	{(const unsigned char*)"EqualTilde", 8770},
	{(const unsigned char*)"UnderBar", 818},
	{(const unsigned char*)"SHcy", 1064},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"ZHcy", 1046},
	{(const unsigned char*)"gel", 8923},
	{(const unsigned char*)"Vee", 8897},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"subne", 8842},
	{NULL, 0},
	{(const unsigned char*)"ngtr", 8815},
	{(const unsigned char*)"isins", 8948},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"angle", 8736},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"ThinSpace", 8201},
	{(const unsigned char*)"samalg", 8720},
	{NULL, 0},
	{(const unsigned char*)"supseteqq", 10950},
	{(const unsigned char*)"SucceedsEqual", 10928},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"vee", 8744},
	{NULL, 0},
	{(const unsigned char*)"approxeq", 8778},
	{(const unsigned char*)"leftarrowtail", 8610},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"dHar", 10597},
	{(const unsigned char*)"andand", 10837},
	{(const unsigned char*)"dlarr", 8601},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"circeq", 8791},
	{NULL, 0},
	{(const unsigned char*)"Lsh", 8624},
	{(const unsigned char*)"laquo", 171},
	{(const unsigned char*)"coloneq", 8788},
	{(const unsigned char*)"llarr", 8647},
	{(const unsigned char*)"Int", 8748},
	{(const unsigned char*)"nlarr", 8602},
	{(const unsigned char*)"Rsh", 8625},
	{(const unsigned char*)"varepsilon", 949},
	{(const unsigned char*)"olarr", 8634},
	{(const unsigned char*)"raquo", 187},
	{(const unsigned char*)"slarr", 8592},
	{(const unsigned char*)"rlarr", 8644},
	{(const unsigned char*)"boxuR", 9560},
	{(const unsigned char*)"minus", 8722},
	{(const unsigned char*)"xlarr", 10229},
	{(const unsigned char*)"lHar", 10594},
	{(const unsigned char*)"rHar", 10596},
	{(const unsigned char*)"subseteqq", 10949},
	{NULL, 0},
	{(const unsigned char*)"uHar", 10595},
	{(const unsigned char*)"epsis", 1013},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"ssetmn", 8726},
	{(const unsigned char*)"equals", 61},
	{NULL, 0},
	{(const unsigned char*)"NotExists", 8708},
	{(const unsigned char*)"prnsim", 8936},
	{(const unsigned char*)"lsh", 8624},
	{(const unsigned char*)"curlyeqsucc", 8927},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"int", 8747},
	{NULL, 0},
	{(const unsigned char*)"rsh", 8625},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"LessSlantEqual", 10877},
	{(const unsigned char*)"DiacriticalDot", 729},
	{NULL, 0},
	{(const unsigned char*)"nvDash", 8877},
	{(const unsigned char*)"prnap", 10937},
	{(const unsigned char*)"ZeroWidthSpace", 8203},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"oplus", 8853},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"middot", 183},
	{NULL, 0},
	{(const unsigned char*)"emptyset", 8709},
	{(const unsigned char*)"uplus", 8846},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"boxhu", 9524},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"softcy", 1100},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"squarf", 9642},
	{(const unsigned char*)"TripleDot", 8411},
	{(const unsigned char*)"DownTee", 8868},
	{(const unsigned char*)"cir", 9675},
	{(const unsigned char*)"expectation", 8496},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"cirfnint", 10768},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"sfrown", 8994},
	{(const unsigned char*)"ntriangleright", 8939},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"nisd", 8954},
	{(const unsigned char*)"dash", 8208},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"nvHarr", 10500},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"hybull", 8259},
	{(const unsigned char*)"RightArrowBar", 8677},
	{(const unsigned char*)"leftrightsquigarrow", 8621},
	{(const unsigned char*)"minusb", 8863},
	{NULL, 0},
	{(const unsigned char*)"frac38", 8540},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"centerdot", 183},
	{(const unsigned char*)"nwnear", 10535},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"larrpl", 10553},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"hookleftarrow", 8617},
	{(const unsigned char*)"hellip", 8230},
	{(const unsigned char*)"rarrpl", 10565},
	{(const unsigned char*)"mid", 8739},
	{NULL, 0},
	{(const unsigned char*)"oast", 8859},
	{(const unsigned char*)"NotTildeTilde", 8777},
	{NULL, 0},
	{(const unsigned char*)"NotTilde", 8769},
	{(const unsigned char*)"ohacgr", 974},
	{(const unsigned char*)"marker", 9646},
	{(const unsigned char*)"langle", 9001},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"vellip", 8942},
	{(const unsigned char*)"NotRightTriangleEqual", 8941},
	{(const unsigned char*)"rangle", 9002},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"gnsim", 8935},
	{(const unsigned char*)"malt", 10016},
	{(const unsigned char*)"times", 215},
	{(const unsigned char*)"RightDownTeeVector", 10589},
	{NULL, 0},
	{(const unsigned char*)"lnsim", 8934},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"preceq", 10927},
	{(const unsigned char*)"equiv", 8801},
	{(const unsigned char*)"geqq", 8807},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Iota", 921},
	{(const unsigned char*)"leqq", 8806},
	{NULL, 0},
	{(const unsigned char*)"cuepr", 8926},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"boxtimes", 8864},
	{(const unsigned char*)"numero", 8470},
	{(const unsigned char*)"setmn", 8726},
	{NULL, 0},
	{(const unsigned char*)"ForAll", 8704},
	{NULL, 0},
	{(const unsigned char*)"excl", 33},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"bsol", 92},
	{(const unsigned char*)"imof", 8887},
	{(const unsigned char*)"dsol", 10742},
	{(const unsigned char*)"ic", 8291},
	{(const unsigned char*)"ReverseElement", 8715},
	{(const unsigned char*)"Exists", 8707},
	{NULL, 0},
	{(const unsigned char*)"parsl", 11005},
	{(const unsigned char*)"bprime", 8245},
	{(const unsigned char*)"Ccedil", 199},
	{(const unsigned char*)"sc", 8827},
	{(const unsigned char*)"propto", 8733},
	{NULL, 0},
	{(const unsigned char*)"osol", 8856},
	{(const unsigned char*)"RightVectorBar", 10579},
	{(const unsigned char*)"iota", 953},
	{(const unsigned char*)"boxDR", 9556},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Theta", 920},
	{(const unsigned char*)"lharu", 8636},
	{(const unsigned char*)"Because", 8757},
	{(const unsigned char*)"qprime", 8279},
	{(const unsigned char*)"simrarr", 10610},
	{NULL, 0},
	{(const unsigned char*)"tprime", 8244},
	{(const unsigned char*)"rharu", 8640},
	{(const unsigned char*)"vprime", 8242},
	{(const unsigned char*)"YUcy", 1070},
	{(const unsigned char*)"plusmn", 177},
	{NULL, 0},
	{(const unsigned char*)"planckh", 8462},
	{(const unsigned char*)"YIcy", 1031},
	{NULL, 0},
	{(const unsigned char*)"NotRightTriangle", 8939},
	{(const unsigned char*)"becaus", 8757},
	{NULL, 0},
	{(const unsigned char*)"PrecedesEqual", 10927},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"nsupe", 8841},
	{(const unsigned char*)"ccedil", 231},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"yacy", 1103},
	{(const unsigned char*)"succnsim", 8937},
	{(const unsigned char*)"theta", 952},
	{(const unsigned char*)"because", 8757},
	{(const unsigned char*)"pre", 10927},
	{NULL, 0},
	{(const unsigned char*)"sharp", 9839},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"timesb", 8864},
	{(const unsigned char*)"Longleftarrow", 10232},
	{(const unsigned char*)"Sqrt", 8730},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Vert", 8214},
	{NULL, 0},
	{(const unsigned char*)"Rho", 929},
	{NULL, 0},
	{(const unsigned char*)"LeftDownTeeVector", 10593},
	{(const unsigned char*)"erDot", 8787},
	{NULL, 0},
	{(const unsigned char*)"integers", 8484},
	{(const unsigned char*)"Dot", 168},
	{(const unsigned char*)"eqvparsl", 10725},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"efDot", 8786},
	{NULL, 0},
	{(const unsigned char*)"NewLine", 10},
	{(const unsigned char*)"sbquo", 8218},
	{NULL, 0},
	{(const unsigned char*)"Diamond", 8900},
	{(const unsigned char*)"Not", 10988},
	{NULL, 0},
	{(const unsigned char*)"Eta", 919},
	{(const unsigned char*)"longleftarrow", 10229},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"starf", 9733},
	{(const unsigned char*)"RoundImplies", 10608},
	{(const unsigned char*)"RightAngleBracket", 9002},
	{NULL, 0},
	{(const unsigned char*)"diamondsuit", 9830},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"vert", 124},
	{(const unsigned char*)"eth", 240},
	{(const unsigned char*)"NotReverseElement", 8716},
	{(const unsigned char*)"Longleftrightarrow", 10234},
	{(const unsigned char*)"ssmile", 8995},
	{(const unsigned char*)"bot", 8869},
	{(const unsigned char*)"supe", 8839},
	{(const unsigned char*)"dot", 729},
	{(const unsigned char*)"pointint", 10773},
	{(const unsigned char*)"intercal", 8890},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"rho", 961},
	{NULL, 0},
	{(const unsigned char*)"primes", 8473},
	{(const unsigned char*)"fllig", 64258},
	{NULL, 0},
	{(const unsigned char*)"diamond", 8900},
	{(const unsigned char*)"not", 172},
	{(const unsigned char*)"precapprox", 10935},
	{(const unsigned char*)"eta", 951},
	{NULL, 0},
	{(const unsigned char*)"backprime", 8245},
	{(const unsigned char*)"GreaterEqualLess", 8923},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"RightTeeArrow", 8614},
	{(const unsigned char*)"boxHd", 9572},
	{(const unsigned char*)"Gammad", 988},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Assign", 8788},
	{(const unsigned char*)"squf", 9642},
	{(const unsigned char*)"angzarr", 9084},
	{(const unsigned char*)"longleftrightarrow", 10231},
	{NULL, 0},
	{(const unsigned char*)"pound", 163},
	{(const unsigned char*)"topbot", 9014},
	{(const unsigned char*)"twoheadleftarrow", 8606},
	{(const unsigned char*)"Congruent", 8801},
	{(const unsigned char*)"nshortparallel", 8742},
	{(const unsigned char*)"LeftArrowRightArrow", 8646},
	{NULL, 0},
	{(const unsigned char*)"sube", 8838},
	{NULL, 0},
	{(const unsigned char*)"hamilt", 8459},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"harrcir", 10568},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"boxV", 9553},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"gammad", 989},
	{(const unsigned char*)"OpenCurlyDoubleQuote", 8220},
	{NULL, 0},
	{(const unsigned char*)"target", 8982},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"bigsqcup", 10758},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"boxVr", 9567},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"eegr", 951},
	{(const unsigned char*)"awint", 10769},
	{(const unsigned char*)"EEacgr", 905},
	{(const unsigned char*)"cwint", 8753},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"RightVector", 8640},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Vvdash", 8874},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Aacute", 193},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Eacute", 201},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Iacute", 205},
	{(const unsigned char*)"boxHU", 9577},
	{(const unsigned char*)"daleth", 8504},
	{(const unsigned char*)"olcross", 10683},
	{(const unsigned char*)"eqcirc", 8790},
	{NULL, 0},
	{(const unsigned char*)"Oacute", 211},
	{(const unsigned char*)"bigodot", 10752},
	{(const unsigned char*)"notinva", 8713},
	{(const unsigned char*)"LeftRightArrow", 8596},
	{(const unsigned char*)"lozenge", 9674},
	{NULL, 0},
	{(const unsigned char*)"Uacute", 218},
	{(const unsigned char*)"nvdash", 8876},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Yacute", 221},
	{(const unsigned char*)"boxvL", 9569},
	{(const unsigned char*)"Bscr", 8492},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Escr", 8496},
	{(const unsigned char*)"Fscr", 8497},
	{(const unsigned char*)"Hacek", 711},
	{(const unsigned char*)"Hscr", 8459},
	{(const unsigned char*)"Iscr", 8464},
	{(const unsigned char*)"boxVh", 9579},
	{(const unsigned char*)"aacute", 225},
	{(const unsigned char*)"Lscr", 8466},
	{(const unsigned char*)"Mscr", 8499},
	{(const unsigned char*)"Downarrow", 8659},
	{(const unsigned char*)"eacute", 233},
	{(const unsigned char*)"iacute", 237},
	{(const unsigned char*)"VerticalLine", 124},
	{(const unsigned char*)"Rscr", 8475},
	{(const unsigned char*)"ap", 8776},
	{(const unsigned char*)"NegativeVeryThinSpace", 8203},
	{(const unsigned char*)"LessTilde", 8818},
	{(const unsigned char*)"oacute", 243},
	{(const unsigned char*)"blk12", 9618},
	{(const unsigned char*)"frac25", 8534},
	{(const unsigned char*)"mp", 8723},
	{(const unsigned char*)"fnof", 402},
	{(const unsigned char*)"Conint", 8751},
	{(const unsigned char*)"uacute", 250},
	{(const unsigned char*)"dd", 8518},
	{(const unsigned char*)"scsim", 8831},
	{(const unsigned char*)"NotSucceeds", 8833},
	{(const unsigned char*)"yacute", 253},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"wp", 8472},
	{(const unsigned char*)"infin", 8734},
	{(const unsigned char*)"escr", 8495},
	{NULL, 0},
	{(const unsigned char*)"DJcy", 1026},
	{(const unsigned char*)"gscr", 8458},
	{(const unsigned char*)"LowerRightArrow", 8600},
	{(const unsigned char*)"GJcy", 1027},
	{(const unsigned char*)"dzcy", 1119},
	{(const unsigned char*)"brvbar", 166},
	{(const unsigned char*)"sqcup", 8852},
	{(const unsigned char*)"KJcy", 1036},
	{(const unsigned char*)"LJcy", 1033},
	{(const unsigned char*)"oscr", 8500},
	{(const unsigned char*)"NJcy", 1034},
	{(const unsigned char*)"ddagger", 8225},
	{(const unsigned char*)"Agrave", 192},
	{(const unsigned char*)"downarrow", 8595},
	{NULL, 0},
	{(const unsigned char*)"duhar", 10607},
	{(const unsigned char*)"Egrave", 200},
	{(const unsigned char*)"Oslash", 216},
	{NULL, 0},
	{(const unsigned char*)"preccurlyeq", 8828},
	{(const unsigned char*)"Igrave", 204},
	{(const unsigned char*)"conint", 8750},
	{(const unsigned char*)"drbkarow", 10512},
	{(const unsigned char*)"DownRightTeeVector", 10591},
	{(const unsigned char*)"odot", 8857},
	{NULL, 0},
	{(const unsigned char*)"Ograve", 210},
	{(const unsigned char*)"ldot", 8918},
	{(const unsigned char*)"LeftAngleBracket", 9001},
	{(const unsigned char*)"tdot", 8411},
	{(const unsigned char*)"idiagr", 912},
	{(const unsigned char*)"sdot", 8901},
	{(const unsigned char*)"Ugrave", 217},
	{(const unsigned char*)"triangleleft", 9667},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"diam", 8900},
	{(const unsigned char*)"commat", 64},
	{(const unsigned char*)"udiagr", 944},
	{(const unsigned char*)"larrb", 8676},
	{(const unsigned char*)"hslash", 8463},
	{(const unsigned char*)"rightleftarrows", 8644},
	{(const unsigned char*)"succnapprox", 10938},
	{(const unsigned char*)"agrave", 224},
	{NULL, 0},
	{(const unsigned char*)"egs", 10902},
	{NULL, 0},
	{(const unsigned char*)"egrave", 232},
	{(const unsigned char*)"oslash", 248},
	{NULL, 0},
	{(const unsigned char*)"nge", 8817},
	{(const unsigned char*)"igrave", 236},
	{(const unsigned char*)"hbar", 8463},
	{NULL, 0},
	{(const unsigned char*)"NestedLessLess", 8810},
	{NULL, 0},
	{(const unsigned char*)"nexist", 8708},
	{(const unsigned char*)"ograve", 242},
	{NULL, 0},
	{(const unsigned char*)"ldquor", 8222},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"rdquor", 8221},
	{(const unsigned char*)"ugrave", 249},
	{(const unsigned char*)"div", 247},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"blacktriangledown", 9662},
	{(const unsigned char*)"UpArrow", 8593},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"niv", 8715},
	{(const unsigned char*)"llhard", 10603},
	{(const unsigned char*)"boxdl", 9488},
	{(const unsigned char*)"piv", 982},
	{NULL, 0},
	{(const unsigned char*)"NotPrecedes", 8832},
	{(const unsigned char*)"lbarr", 10508},
	{NULL, 0},
	{(const unsigned char*)"andd", 10844},
	{(const unsigned char*)"bigwedge", 8896},
	{(const unsigned char*)"InvisibleTimes", 8290},
	{NULL, 0},
	{(const unsigned char*)"rbarr", 10509},
	{NULL, 0},
	{(const unsigned char*)"ApplyFunction", 8289},
	{(const unsigned char*)"bottom", 8869},
	{(const unsigned char*)"awconint", 8755},
	{(const unsigned char*)"cwconint", 8754},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"dwangle", 10662},
	{(const unsigned char*)"rarrb", 8677},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"UpArrowBar", 10514},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"realine", 8475},
	{(const unsigned char*)"uwangle", 10663},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"lowbar", 95},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Cayleys", 8493},
	{NULL, 0},
	{(const unsigned char*)"bigstar", 9733},
	{(const unsigned char*)"isin", 8712},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"backepsilon", 1014},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"OpenCurlyQuote", 8216},
	{NULL, 0},
	{(const unsigned char*)"Cross", 10799},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"lesseqgtr", 8922},
	{(const unsigned char*)"Upsi", 978},
	{(const unsigned char*)"DoubleRightArrow", 8658},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Laplacetrf", 8466},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"bigcirc", 9711},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"epsi", 1013},
	{(const unsigned char*)"LeftTeeVector", 10586},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"DoubleUpDownArrow", 8661},
	{NULL, 0},
	{(const unsigned char*)"DiacriticalGrave", 96},
	{(const unsigned char*)"triangle", 9653},
	{NULL, 0},
	{(const unsigned char*)"permil", 8240},
	{NULL, 0},
	{(const unsigned char*)"lpargt", 10656},
	{(const unsigned char*)"UpEquilibrium", 10606},
	{(const unsigned char*)"backsimeq", 8909},
	{(const unsigned char*)"Supset", 8913},
	{(const unsigned char*)"boxUr", 9561},
	{(const unsigned char*)"sccue", 8829},
	{(const unsigned char*)"rpargt", 10644},
	{(const unsigned char*)"cross", 10007},
	{(const unsigned char*)"upsi", 965},
	{NULL, 0},
	{(const unsigned char*)"cularr", 8630},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"varkappa", 1008},
	{(const unsigned char*)"half", 189},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"sfgr", 962},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"ImaginaryI", 8520},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Tau", 932},
	{(const unsigned char*)"bernou", 8492},
	{(const unsigned char*)"DoubleLeftArrow", 8656},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"supset", 8835},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"MediumSpace", 8287},
	{NULL, 0},
	{(const unsigned char*)"Subset", 8912},
	{(const unsigned char*)"NegativeThickSpace", 8203},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"boxuL", 9563},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"notin", 8713},
	{NULL, 0},
	{(const unsigned char*)"Re", 8476},
	{NULL, 0},
	{(const unsigned char*)"nleq", 8816},
	{(const unsigned char*)"nLeftrightarrow", 8654},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Beta", 914},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"dollar", 36},
	{(const unsigned char*)"Product", 8719},
	{(const unsigned char*)"tau", 964},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Poincareplane", 8460},
	{(const unsigned char*)"ee", 8519},
	{(const unsigned char*)"CenterDot", 183},
	{(const unsigned char*)"Jsercy", 1032},
	{(const unsigned char*)"ge", 8805},
	{(const unsigned char*)"Rarrtl", 10518},
	{(const unsigned char*)"subset", 8834},
	{NULL, 0},
	{(const unsigned char*)"le", 8804},
	{NULL, 0},
	{(const unsigned char*)"ne", 8800},
	{(const unsigned char*)"mapstoleft", 8612},
	{(const unsigned char*)"NotSucceedsSlantEqual", 8929},
	{(const unsigned char*)"upsih", 978},
	{(const unsigned char*)"cedil", 184},
	{(const unsigned char*)"Zeta", 918},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"apos", 39},
	{(const unsigned char*)"nsube", 8840},
	{(const unsigned char*)"beta", 946},
	{(const unsigned char*)"frac78", 8542},
	{(const unsigned char*)"nltri", 8938},
	{(const unsigned char*)"iiiint", 10764},
	{NULL, 0},
	{(const unsigned char*)"veebar", 8891},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"RightTeeVector", 10587},
	{(const unsigned char*)"Dagger", 8225},
	{(const unsigned char*)"vltri", 8882},
	{(const unsigned char*)"larrtl", 8610},
	{(const unsigned char*)"iocy", 1105},
	{(const unsigned char*)"dashv", 8867},
	{(const unsigned char*)"frac12", 189},
	{(const unsigned char*)"GreaterLess", 8823},
	{(const unsigned char*)"jsercy", 1112},
	{(const unsigned char*)"rarrtl", 8611},
	{(const unsigned char*)"oline", 8254},
	{(const unsigned char*)"sup3", 179},
	{(const unsigned char*)"emsp13", 8196},
	{(const unsigned char*)"asymp", 8776},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"zeta", 950},
	{(const unsigned char*)"UpperRightArrow", 8599},
	{NULL, 0},
	{(const unsigned char*)"smallsetminus", 8726},
	{(const unsigned char*)"LeftUpTeeVector", 10592},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"dagger", 8224},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"LeftDownVector", 8643},
	{(const unsigned char*)"sime", 8771},
	{(const unsigned char*)"precsim", 8830},
	{(const unsigned char*)"MinusPlus", 8723},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"LeftVector", 8636},
	{NULL, 0},
	{(const unsigned char*)"profalar", 9006},
	{(const unsigned char*)"dtri", 9663},
	{(const unsigned char*)"between", 8812},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"hyphen", 8208},
	{NULL, 0},
	{(const unsigned char*)"NegativeThinSpace", 8203},
	{(const unsigned char*)"downdownarrows", 8650},
	{(const unsigned char*)"xmap", 10236},
	{(const unsigned char*)"ltri", 9667},
	{(const unsigned char*)"bdquo", 8222},
	{(const unsigned char*)"notinvb", 8951},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"rtri", 9657},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"hoarr", 8703},
	{(const unsigned char*)"plusdo", 8724},
	{(const unsigned char*)"ldquo", 8220},
	{(const unsigned char*)"bigoplus", 10753},
	{(const unsigned char*)"loarr", 8701},
	{(const unsigned char*)"natur", 9838},
	{(const unsigned char*)"utri", 9653},
	{NULL, 0},
	{(const unsigned char*)"rdquo", 8221},
	{NULL, 0},
	{(const unsigned char*)"roarr", 8702},
	{(const unsigned char*)"VerticalBar", 8739},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"NotPrecedesSlantEqual", 8928},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"imped", 437},
	{(const unsigned char*)"thinsp", 8201},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"dArr", 8659},
	{(const unsigned char*)"dlcorn", 8990},
	{NULL, 0},
	{(const unsigned char*)"LeftUpDownVector", 10577},
	{(const unsigned char*)"hArr", 8660},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"lArr", 8656},
	{(const unsigned char*)"ltimes", 8905},
	{NULL, 0},
	{(const unsigned char*)"rightharpoondown", 8641},
	{(const unsigned char*)"otimes", 8855},
	{(const unsigned char*)"RightTee", 8866},
	{(const unsigned char*)"rArr", 8658},
	{(const unsigned char*)"rtimes", 8906},
	{(const unsigned char*)"varsigma", 962},
	{(const unsigned char*)"uArr", 8657},
	{(const unsigned char*)"ulcorn", 8988},
	{(const unsigned char*)"vArr", 8661},
	{(const unsigned char*)"szlig", 223},
	{(const unsigned char*)"Vdash", 8873},
	{(const unsigned char*)"nspar", 8742},
	{(const unsigned char*)"bsim", 8765},
	{(const unsigned char*)"LeftTriangleBar", 10703},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"gsim", 8819},
	{(const unsigned char*)"lcub", 123},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"isinE", 8953},
	{(const unsigned char*)"lsim", 8818},
	{NULL, 0},
	{(const unsigned char*)"rcub", 125},
	{(const unsigned char*)"boxH", 9552},
	{NULL, 0},
	{(const unsigned char*)"nsim", 8769},
	{(const unsigned char*)"bkarow", 10509},
	{(const unsigned char*)"mdash", 8212},
	{(const unsigned char*)"odash", 8861},
	{(const unsigned char*)"clubsuit", 9827},
	{(const unsigned char*)"bigcup", 8899},
	{(const unsigned char*)"nwarhk", 10531},
	{(const unsigned char*)"boxDL", 9559},
	{(const unsigned char*)"ndash", 8211},
	{NULL, 0},
	{(const unsigned char*)"vdash", 8866},
	{(const unsigned char*)"swarhk", 10534},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"blacklozenge", 10731},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"DoubleLeftRightArrow", 8660},
	{NULL, 0},
	{(const unsigned char*)"naturals", 8469},
	{(const unsigned char*)"incare", 8453},
	{NULL, 0},
	{(const unsigned char*)"RightUpDownVector", 10575},
	{NULL, 0},
	{(const unsigned char*)"zwnj", 8204},
	{(const unsigned char*)"nprec", 8832},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"circledast", 8859},
	{NULL, 0},
	{(const unsigned char*)"heartsuit", 9829},
	{(const unsigned char*)"esdot", 8784},
	{(const unsigned char*)"bigtriangledown", 9661},
	{(const unsigned char*)"Uparrow", 8657},
	{(const unsigned char*)"gsdot", 8919},
	{(const unsigned char*)"Coproduct", 8720},
	{NULL, 0},
	{(const unsigned char*)"circledcirc", 8858},
	{(const unsigned char*)"oint", 8750},
	{(const unsigned char*)"qint", 10764},
	{NULL, 0},
	{(const unsigned char*)"ldsh", 8626},
	{(const unsigned char*)"trade", 8482},
	{(const unsigned char*)"lrhar2", 8651},
	{(const unsigned char*)"larrhk", 8617},
	{(const unsigned char*)"tint", 8749},
	{NULL, 0},
	{(const unsigned char*)"rdsh", 8627},
	{(const unsigned char*)"psgr", 968},
	{(const unsigned char*)"rarrhk", 8618},
	{(const unsigned char*)"Psi", 936},
	{NULL, 0},
	{(const unsigned char*)"larrsim", 10611},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Epsilon", 917},
	{NULL, 0},
	{(const unsigned char*)"rarrsim", 10612},
	{(const unsigned char*)"male", 9794},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"uparrow", 8593},
	{(const unsigned char*)"Scaron", 352},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Upsilon", 933},
	{NULL, 0},
	{(const unsigned char*)"hearts", 9829},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"eqsim", 8770},
	{(const unsigned char*)"Sigma", 931},
	{(const unsigned char*)"Or", 10836},
	{(const unsigned char*)"UpArrowDownArrow", 8645},
	{(const unsigned char*)"twixt", 8812},
	{(const unsigned char*)"psi", 968},
	{NULL, 0},
	{(const unsigned char*)"nabla", 8711},
	{(const unsigned char*)"bowtie", 8904},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"epsilon", 949},
	{NULL, 0},
	{(const unsigned char*)"GreaterSlantEqual", 10878},
	{(const unsigned char*)"NotLeftTriangleEqual", 8940},
	{(const unsigned char*)"apacir", 10863},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"upharpoonright", 8638},
	{NULL, 0},
	{(const unsigned char*)"scaron", 353},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"af", 8289},
	{(const unsigned char*)"upsilon", 965},
	{(const unsigned char*)"TildeEqual", 8771},
	{NULL, 0},
	{(const unsigned char*)"Lambda", 923},
	{(const unsigned char*)"neArr", 8663},
	{(const unsigned char*)"sigma", 963},
	{(const unsigned char*)"ETH", 208},
	{(const unsigned char*)"leftthreetimes", 8907},
	{(const unsigned char*)"seArr", 8664},
	{(const unsigned char*)"thicksim", 8764},
	{(const unsigned char*)"bigcap", 8898},
	{(const unsigned char*)"ang", 8736},
	{(const unsigned char*)"ldca", 10550},
	{(const unsigned char*)"rdca", 10551},
	{(const unsigned char*)"wr", 8768},
	{NULL, 0},
	{(const unsigned char*)"or", 8744},
	{(const unsigned char*)"pr", 8826},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"triangleq", 8796},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"gtrsim", 8819},
	{(const unsigned char*)"looparrowleft", 8619},
	{(const unsigned char*)"LongRightArrow", 10230},
	{(const unsigned char*)"nis", 8956},
	{(const unsigned char*)"Aring", 197},
	{(const unsigned char*)"LeftDownVectorBar", 10585},
	{(const unsigned char*)"NotTildeEqual", 8772},
	{(const unsigned char*)"lambda", 955},
	{(const unsigned char*)"larrlp", 8619},
	{(const unsigned char*)"leftharpoondown", 8637},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"sup2", 178},
	{NULL, 0},
	{(const unsigned char*)"rarrlp", 8620},
	{(const unsigned char*)"SmallCircle", 8728},
	{(const unsigned char*)"bNot", 10989},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"aleph", 8501},
	{(const unsigned char*)"blacktriangle", 9652},
	{NULL, 0},
	{(const unsigned char*)"circleddash", 8861},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"rhov", 1009},
	{NULL, 0},
	{(const unsigned char*)"UpTee", 8869},
	{(const unsigned char*)"die", 168},
	{(const unsigned char*)"bump", 8782},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"epar", 8917},
	{(const unsigned char*)"gnap", 10890},
	{(const unsigned char*)"RightFloor", 8971},
	{(const unsigned char*)"aring", 229},
	{NULL, 0},
	{(const unsigned char*)"lnap", 10889},
	{(const unsigned char*)"approx", 8776},
	{(const unsigned char*)"larrbfs", 10527},
	{(const unsigned char*)"lpar", 40},
	{(const unsigned char*)"npar", 8742},
	{(const unsigned char*)"gEl", 10892},
	{(const unsigned char*)"boxVl", 9570},
	{(const unsigned char*)"eqcolon", 8789},
	{(const unsigned char*)"rarrbfs", 10528},
	{(const unsigned char*)"rpar", 41},
	{(const unsigned char*)"spar", 8741},
	{(const unsigned char*)"thksim", 8764},
	{NULL, 0},
	{(const unsigned char*)"RightDownVectorBar", 10581},
	{NULL, 0},
	{(const unsigned char*)"para", 182},
	{(const unsigned char*)"thkap", 8776},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Superset", 8835},
	{NULL, 0},
	{(const unsigned char*)"ddarr", 8650},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Gamma", 915},
	{(const unsigned char*)"frac15", 8533},
	{(const unsigned char*)"kappav", 1008},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"udarr", 8645},
	{(const unsigned char*)"Therefore", 8756},
	{(const unsigned char*)"hairsp", 8202},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"CircleMinus", 8854},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"ordf", 170},
	{(const unsigned char*)"VerticalTilde", 8768},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"LeftVectorBar", 10578},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"UnderBracket", 9141},
	{NULL, 0},
	{(const unsigned char*)"gamma", 947},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"DoubleDot", 168},
	{(const unsigned char*)"lceil", 8968},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"curlyeqprec", 8926},
	{(const unsigned char*)"varnothing", 8709},
	{(const unsigned char*)"nhpar", 10994},
	{(const unsigned char*)"therefore", 8756},
	{(const unsigned char*)"dlcrop", 8973},
	{(const unsigned char*)"rceil", 8969},
	{(const unsigned char*)"leftleftarrows", 8647},
	{(const unsigned char*)"vangrt", 10652},
	{NULL, 0},
	{(const unsigned char*)"lrm", 8206},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"curvearrowright", 8631},
	{(const unsigned char*)"thetas", 952},
	{(const unsigned char*)"PartialD", 8706},
	{(const unsigned char*)"nVDash", 8879},
	{(const unsigned char*)"wedgeq", 8793},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"ulcrop", 8975},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"zigrarr", 8669},
	{(const unsigned char*)"lozf", 10731},
	{(const unsigned char*)"sung", 9834},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"iff", 8660},
	{(const unsigned char*)"xnis", 8955},
	{(const unsigned char*)"ring", 730},
	{(const unsigned char*)"dfisht", 10623},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"nltrie", 8940},
	{(const unsigned char*)"llcorner", 8990},
	{NULL, 0},
	{(const unsigned char*)"lfisht", 10620},
	{(const unsigned char*)"ctdot", 8943},
	{(const unsigned char*)"dtdot", 8945},
	{(const unsigned char*)"CloseCurlyQuote", 8217},
	{(const unsigned char*)"par", 8741},
	{NULL, 0},
	{(const unsigned char*)"rfisht", 10621},
	{(const unsigned char*)"ulcorner", 8988},
	{NULL, 0},
	{(const unsigned char*)"ufisht", 10622},
	{NULL, 0},
	{(const unsigned char*)"notinvc", 8950},
	{(const unsigned char*)"orderof", 8500},
	{NULL, 0},
	{(const unsigned char*)"Rrightarrow", 8667},
	{(const unsigned char*)"emsp", 8195},
	{(const unsigned char*)"Chi", 935},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"utdot", 8944},
	{(const unsigned char*)"bull", 8226},
	{NULL, 0},
	{(const unsigned char*)"khgr", 967},
	{(const unsigned char*)"ominus", 8854},
	{(const unsigned char*)"eqslantgtr", 10902},
	{(const unsigned char*)"multimap", 8888},
	{(const unsigned char*)"lowast", 8727},
	{(const unsigned char*)"ohgr", 969},
	{(const unsigned char*)"NotLess", 8814},
	{(const unsigned char*)"alefsym", 8501},
	{(const unsigned char*)"Phi", 934},
	{(const unsigned char*)"thgr", 952},
	{NULL, 0},
	{(const unsigned char*)"isinsv", 8947},
	{(const unsigned char*)"OHacgr", 911},
	{NULL, 0},
	{(const unsigned char*)"NotElement", 8713},
	{(const unsigned char*)"nearrow", 8599},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"DoubleLeftTee", 10980},
	{(const unsigned char*)"nrightarrow", 8603},
	{NULL, 0},
	{(const unsigned char*)"searrow", 8600},
	{(const unsigned char*)"UpTeeArrow", 8613},
	{NULL, 0},
	{(const unsigned char*)"dbkarow", 10511},
	{(const unsigned char*)"period", 46},
	{(const unsigned char*)"Gg", 8921},
	{(const unsigned char*)"circledR", 174},
	{(const unsigned char*)"DownBreve", 785},
	{NULL, 0},
	{(const unsigned char*)"imagline", 8464},
	{(const unsigned char*)"gneq", 10888},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"chi", 967},
	{NULL, 0},
	{(const unsigned char*)"lneq", 10887},
	{(const unsigned char*)"phi", 981},
	{NULL, 0},
	{(const unsigned char*)"spadesuit", 9824},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"prsim", 8830},
	{(const unsigned char*)"Atilde", 195},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"isinv", 8712},
	{(const unsigned char*)"rlarr2", 8644},
	{(const unsigned char*)"nrArr", 8655},
	{NULL, 0},
	{(const unsigned char*)"angst", 8491},
	{NULL, 0},
	{(const unsigned char*)"sdotb", 8865},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Ntilde", 209},
	{(const unsigned char*)"gg", 8811},
	{(const unsigned char*)"xrArr", 10233},
	{(const unsigned char*)"DoubleLongLeftRightArrow", 10234},
	{(const unsigned char*)"Otilde", 213},
	{NULL, 0},
	{(const unsigned char*)"lg", 8822},
	{(const unsigned char*)"LeftArrowBar", 8676},
	{(const unsigned char*)"thickapprox", 8776},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"precnsim", 8936},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Element", 8712},
	{(const unsigned char*)"atilde", 227},
	{NULL, 0},
	{(const unsigned char*)"LessEqualGreater", 8922},
	{NULL, 0},
	{(const unsigned char*)"eqslantless", 10901},
	{(const unsigned char*)"EmptyVerySmallSquare", 9643},
	{(const unsigned char*)"phgr", 966},
	{(const unsigned char*)"epsiv", 949},
	{(const unsigned char*)"DoubleVerticalBar", 8741},
	{(const unsigned char*)"LeftTriangle", 8882},
	{NULL, 0},
	{(const unsigned char*)"spades", 9824},
	{(const unsigned char*)"frac23", 8532},
	{(const unsigned char*)"ntilde", 241},
	{(const unsigned char*)"otilde", 245},
	{NULL, 0},
	{(const unsigned char*)"sup1", 185},
	{(const unsigned char*)"GreaterGreater", 10914},
	{(const unsigned char*)"iecy", 1077},
	{(const unsigned char*)"NestedGreaterGreater", 8811},
	{(const unsigned char*)"lfloor", 8970},
	{(const unsigned char*)"SquareSubsetEqual", 8849},
	{NULL, 0},
	{(const unsigned char*)"acute", 180},
	{(const unsigned char*)"YAcy", 1071},
	{NULL, 0},
	{(const unsigned char*)"rfloor", 8971},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"quest", 63},
	{NULL, 0},
	{(const unsigned char*)"rlhar", 8652},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"geq", 8805},
	{(const unsigned char*)"CloseCurlyDoubleQuote", 8221},
	{(const unsigned char*)"lsquor", 8218},
	{NULL, 0},
	{(const unsigned char*)"tshcy", 1115},
	{(const unsigned char*)"leq", 8804},
	{(const unsigned char*)"boxUl", 9564},
	{(const unsigned char*)"lurdshar", 10570},
	{(const unsigned char*)"rsquor", 8217},
	{(const unsigned char*)"VerticalSeparator", 10072},
	{(const unsigned char*)"boxdR", 9554},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"scap", 10936},
	{(const unsigned char*)"hkswarow", 10534},
	{NULL, 0},
	{(const unsigned char*)"CapitalDifferentialD", 8517},
	{(const unsigned char*)"NoBreak", 8288},
	{(const unsigned char*)"lthree", 8907},
	{(const unsigned char*)"bigtriangleup", 9651},
	{(const unsigned char*)"elinters", 65533},
	{NULL, 0},
	{(const unsigned char*)"forall", 8704},
	{(const unsigned char*)"NotGreater", 8815},
	{(const unsigned char*)"rthree", 8908},
	{(const unsigned char*)"Jukcy", 1028},
	{NULL, 0},
	{(const unsigned char*)"Iukcy", 1030},
	{NULL, 0},
	{(const unsigned char*)"gtreqqless", 10892},
	{NULL, 0},
	{(const unsigned char*)"UnderParenthesis", 65078},
	{NULL, 0},
	{(const unsigned char*)"nearr", 8599},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"perp", 8869},
	{(const unsigned char*)"bepsi", 1014},
	{(const unsigned char*)"searr", 8600},
	{(const unsigned char*)"iexcl", 161},
	{(const unsigned char*)"LeftArrow", 8592},
	{(const unsigned char*)"NegativeMediumSpace", 8203},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"ast", 42},
	{NULL, 0},
	{(const unsigned char*)"lAarr", 8666},
	{(const unsigned char*)"DownRightVectorBar", 10583},
	{(const unsigned char*)"cuvee", 8910},
	{NULL, 0},
	{(const unsigned char*)"iukcy", 1110},
	{(const unsigned char*)"jukcy", 1108},
	{(const unsigned char*)"latail", 10521},
	{(const unsigned char*)"disin", 8946},
	{NULL, 0},
	{(const unsigned char*)"rAarr", 8667},
	{(const unsigned char*)"angsph", 8738},
	{NULL, 0},
	{(const unsigned char*)"InvisibleComma", 8291},
	{(const unsigned char*)"ratail", 10522},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"supnE", 10956},
	{(const unsigned char*)"ngt", 8815},
	{(const unsigned char*)"order", 8500},
	{(const unsigned char*)"divide", 247},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"colon", 58},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"CirclePlus", 8853},
	{(const unsigned char*)"frac18", 8539},
	{(const unsigned char*)"nsup", 8837},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"intprod", 10812},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"And", 10835},
	{NULL, 0},
	{(const unsigned char*)"Cup", 8915},
	{NULL, 0},
	{(const unsigned char*)"nsimeq", 8772},
	{NULL, 0},
	{(const unsigned char*)"subnE", 10955},
	{NULL, 0},
	{(const unsigned char*)"SHCHcy", 1065},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"LessLess", 10913},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"rightarrowtail", 8611},
	{(const unsigned char*)"EEgr", 919},
	{(const unsigned char*)"Sup", 8913},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"simeq", 8771},
	{(const unsigned char*)"leftharpoonup", 8636},
	{NULL, 0},
	{(const unsigned char*)"boxhd", 9516},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"and", 8743},
	{(const unsigned char*)"Cedilla", 184},
	{(const unsigned char*)"cup", 8746},
	{NULL, 0},
	{(const unsigned char*)"ensp", 8194},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"gimel", 8503},
	{NULL, 0},
	{(const unsigned char*)"straightphi", 981},
	{(const unsigned char*)"nbsp", 160},
	{(const unsigned char*)"NotLessGreater", 8824},
	{(const unsigned char*)"thetav", 977},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"sup", 8835},
	{(const unsigned char*)"lsqb", 91},
	{NULL, 0},
	{(const unsigned char*)"check", 10003},
	{(const unsigned char*)"Gt", 8811},
	{(const unsigned char*)"boxv", 9474},
	{(const unsigned char*)"rsqb", 93},
	{(const unsigned char*)"Implies", 8658},
	{(const unsigned char*)"shortparallel", 8741},
	{(const unsigned char*)"Lt", 8810},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Sub", 8912},
	{NULL, 0},
	{(const unsigned char*)"HARDcy", 1066},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"thorn", 254},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"boxvr", 9500},
	{(const unsigned char*)"DD", 8517},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"nVdash", 8878},
	{(const unsigned char*)"angrt", 8735},
	{(const unsigned char*)"gt", 62},
	{(const unsigned char*)"trianglerighteq", 8885},
	{(const unsigned char*)"sub", 8834},
	{(const unsigned char*)"it", 8290},
	{NULL, 0},
	{(const unsigned char*)"lt", 60},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"cudarrr", 10549},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"DZcy", 1039},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"seswar", 10537},
	{(const unsigned char*)"boxhU", 9576},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"precnapprox", 10937},
	{NULL, 0},
	{(const unsigned char*)"fallingdotseq", 8786},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"vartheta", 977},
	{(const unsigned char*)"digamma", 989},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Omicron", 927},
	{(const unsigned char*)"oror", 10838},
	{NULL, 0},
	{(const unsigned char*)"DownLeftRightVector", 10576},
	{(const unsigned char*)"NonBreakingSpace", 160},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"NotVerticalBar", 8740},
	{NULL, 0},
	{(const unsigned char*)"boxvh", 9532},
	{(const unsigned char*)"smile", 8995},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Bumpeq", 8782},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Proportion", 8759},
	{(const unsigned char*)"eDot", 8785},
	{NULL, 0},
	{(const unsigned char*)"numsp", 8199},
	{NULL, 0},
	{(const unsigned char*)"ShortLeftArrow", 8592},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"omicron", 959},
	{(const unsigned char*)"realpart", 8476},
	{NULL, 0},
	{(const unsigned char*)"HumpEqual", 8783},
	{(const unsigned char*)"RightDoubleBracket", 12315},
	{NULL, 0},
	{(const unsigned char*)"lhard", 8637},
	{NULL, 0},
	{(const unsigned char*)"Union", 8899},
	{(const unsigned char*)"rhard", 8641},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"topcir", 10993},
	{NULL, 0},
	{(const unsigned char*)"Copf", 8450},
	{(const unsigned char*)"bumpeq", 8783},
	{(const unsigned char*)"ntrianglelefteq", 8940},
	{(const unsigned char*)"lsquo", 8216},
	{(const unsigned char*)"drarr", 8600},
	{(const unsigned char*)"erarr", 10609},
	{(const unsigned char*)"crarr", 8629},
	{NULL, 0},
	{(const unsigned char*)"Hopf", 8461},
	{(const unsigned char*)"rsquo", 8217},
	{NULL, 0},
	{(const unsigned char*)"Nopf", 8469},
	{(const unsigned char*)"lrarr", 8646},
	{(const unsigned char*)"Uarrocir", 10569},
	{(const unsigned char*)"nrarr", 8603},
	{(const unsigned char*)"backcong", 8780},
	{(const unsigned char*)"orarr", 8635},
	{(const unsigned char*)"RBarr", 10512},
	{(const unsigned char*)"rrarr", 8649},
	{(const unsigned char*)"srarr", 8594},
	{(const unsigned char*)"Qopf", 8474},
	{(const unsigned char*)"Ropf", 8477},
	{(const unsigned char*)"trianglelefteq", 8884},
	{(const unsigned char*)"Popf", 8473},
	{(const unsigned char*)"xrarr", 10230},
	{NULL, 0},
	{(const unsigned char*)"Zopf", 8484},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"CupCap", 8781},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"comma", 44},
	{(const unsigned char*)"Acy", 1040},
	{(const unsigned char*)"Bcy", 1041},
	{(const unsigned char*)"lBarr", 10510},
	{(const unsigned char*)"HilbertSpace", 8459},
	{(const unsigned char*)"Ecy", 1069},
	{(const unsigned char*)"Fcy", 1060},
	{(const unsigned char*)"Gcy", 1043},
	{(const unsigned char*)"rBarr", 10511},
	{(const unsigned char*)"Icy", 1048},
	{(const unsigned char*)"Jcy", 1049},
	{(const unsigned char*)"Kcy", 1050},
	{(const unsigned char*)"Lcy", 1051},
	{(const unsigned char*)"aelig", 230},
	{(const unsigned char*)"Mcy", 1052},
	{(const unsigned char*)"Ocy", 1054},
	{(const unsigned char*)"Pcy", 1055},
	{(const unsigned char*)"Ncy", 1053},
	{(const unsigned char*)"Rcy", 1056},
	{(const unsigned char*)"Scy", 1057},
	{(const unsigned char*)"ShortUpArrow", 8593},
	{(const unsigned char*)"Ucy", 1059},
	{(const unsigned char*)"Vcy", 1042},
	{(const unsigned char*)"Tcy", 1058},
	{(const unsigned char*)"DiacriticalDoubleAcute", 733},
	{(const unsigned char*)"Alpha", 913},
	{(const unsigned char*)"Ycy", 1067},
	{(const unsigned char*)"Zcy", 1047},
	{(const unsigned char*)"nmid", 8740},
	{(const unsigned char*)"NotSubsetEqual", 8840},
	{(const unsigned char*)"ntrianglerighteq", 8941},
	{(const unsigned char*)"straightepsilon", 1013},
	{(const unsigned char*)"ddotseq", 10871},
	{(const unsigned char*)"acy", 1072},
	{(const unsigned char*)"bcy", 1073},
	{NULL, 0},
	{(const unsigned char*)"dcy", 1076},
	{(const unsigned char*)"ecy", 1101},
	{(const unsigned char*)"gnapprox", 10890},
	{(const unsigned char*)"fcy", 1092},
	{(const unsigned char*)"Dcy", 1044},
	{(const unsigned char*)"icy", 1080},
	{(const unsigned char*)"gcy", 1075},
	{(const unsigned char*)"lnapprox", 10889},
	{(const unsigned char*)"TildeFullEqual", 8773},
	{(const unsigned char*)"jcy", 1081},
	{(const unsigned char*)"kcy", 1082},
	{(const unsigned char*)"lcy", 1083},
	{(const unsigned char*)"ReverseUpEquilibrium", 10607},
	{(const unsigned char*)"ncy", 1085},
	{(const unsigned char*)"ocy", 1086},
	{(const unsigned char*)"ocir", 8858},
	{(const unsigned char*)"scy", 1089},
	{(const unsigned char*)"rcy", 1088},
	{(const unsigned char*)"pcy", 1087},
	{(const unsigned char*)"mcy", 1084},
	{(const unsigned char*)"ucy", 1091},
	{(const unsigned char*)"alpha", 945},
	{(const unsigned char*)"DoubleContourIntegral", 8751},
	{(const unsigned char*)"zcy", 1079},
	{(const unsigned char*)"nshortmid", 8740},
	{(const unsigned char*)"ohm", 8486},
	{(const unsigned char*)"tcy", 1090},
	{(const unsigned char*)"ycy", 1099},
	{(const unsigned char*)"vcy", 1074},
	{(const unsigned char*)"sqsub", 8847},
	{(const unsigned char*)"Udigr", 939},
	{(const unsigned char*)"DownLeftTeeVector", 10590},
	{(const unsigned char*)"udigr", 971},
	{(const unsigned char*)"ecir", 8790},
	{(const unsigned char*)"cularrp", 10557},
	{(const unsigned char*)"idigr", 970},
	{(const unsigned char*)"smid", 8739},
	{(const unsigned char*)"Idigr", 938},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"DoubleLongLeftArrow", 10232},
	{NULL, 0},
	{(const unsigned char*)"SquareSupersetEqual", 8850},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"FilledSmallSquare", 9724},
	{(const unsigned char*)"oelig", 339},
	{(const unsigned char*)"NotGreaterLess", 8825},
	{(const unsigned char*)"b.Gammad", 988},
	{NULL, 0},
	{(const unsigned char*)"rarrap", 10613},
	{NULL, 0},
	{(const unsigned char*)"cylcty", 9005},
	{(const unsigned char*)"ContourIntegral", 8750},
	{(const unsigned char*)"Intersection", 8898},
	{(const unsigned char*)"acd", 8767},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"fltns", 9649},
	{(const unsigned char*)"Lleftarrow", 8666},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"NotSupersetEqual", 8841},
	{NULL, 0},
	{(const unsigned char*)"nvinfin", 10718},
	{(const unsigned char*)"Acirc", 194},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"circlearrowleft", 8634},
	{(const unsigned char*)"Ecirc", 202},
	{(const unsigned char*)"Mu", 924},
	{(const unsigned char*)"Nu", 925},
	{(const unsigned char*)"complexes", 8450},
	{(const unsigned char*)"Icirc", 206},
	{NULL, 0},
	{(const unsigned char*)"NotLeftTriangle", 8938},
	{(const unsigned char*)"dotsquare", 8865},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Ocirc", 212},
	{(const unsigned char*)"swnwar", 10538},
	{(const unsigned char*)"nsucc", 8833},
	{NULL, 0},
	{(const unsigned char*)"Pi", 928},
	{NULL, 0},
	{(const unsigned char*)"Ucirc", 219},
	{(const unsigned char*)"squ", 9633},
	{(const unsigned char*)"boxur", 9492},
	{(const unsigned char*)"Xi", 926},
	{(const unsigned char*)"there4", 8756},
	{(const unsigned char*)"LeftRightVector", 10574},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"nleftarrow", 8602},
	{(const unsigned char*)"NotSquareSubsetEqual", 8930},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"acirc", 226},
	{(const unsigned char*)"leftrightharpoons", 8651},
	{(const unsigned char*)"Omega", 937},
	{(const unsigned char*)"Aacgr", 902},
	{(const unsigned char*)"boxHD", 9574},
	{(const unsigned char*)"ecirc", 234},
	{(const unsigned char*)"nu", 957},
	{(const unsigned char*)"nhArr", 8654},
	{(const unsigned char*)"Mellintrf", 8499},
	{(const unsigned char*)"icirc", 238},
	{(const unsigned char*)"succ", 8827},
	{(const unsigned char*)"mu", 956},
	{NULL, 0},
	{(const unsigned char*)"ni", 8715},
	{(const unsigned char*)"ocirc", 244},
	{(const unsigned char*)"pi", 960},
	{(const unsigned char*)"DiacriticalAcute", 180},
	{(const unsigned char*)"xhArr", 10234},
	{(const unsigned char*)"curlyvee", 8910},
	{(const unsigned char*)"deg", 176},
	{(const unsigned char*)"ucirc", 251},
	{(const unsigned char*)"yen", 165},
	{NULL, 0},
	{(const unsigned char*)"xi", 958},
	{(const unsigned char*)"xcirc", 9711},
	{(const unsigned char*)"IOcy", 1025},
	{(const unsigned char*)"els", 10901},
	{(const unsigned char*)"gE", 8807},
	{(const unsigned char*)"leg", 8922},
	{(const unsigned char*)"Iacgr", 906},
	{(const unsigned char*)"LeftTeeArrow", 8612},
	{(const unsigned char*)"dscy", 1109},
	{(const unsigned char*)"SucceedsSlantEqual", 8829},
	{(const unsigned char*)"fpartint", 10765},
	{(const unsigned char*)"omega", 969},
	{(const unsigned char*)"frac34", 190},
	{(const unsigned char*)"reg", 174},
	{(const unsigned char*)"ShortDownArrow", 8595},
	{(const unsigned char*)"quot", 34},
	{(const unsigned char*)"ell", 8467},
	{(const unsigned char*)"circlearrowright", 8635},
	{(const unsigned char*)"inodot", 305},
	{(const unsigned char*)"xdtri", 9661},
	{(const unsigned char*)"iacgr", 943},
	{(const unsigned char*)"imagpart", 8465},
	{(const unsigned char*)"ldrdhar", 10599},
	{(const unsigned char*)"tscy", 1094},
	{(const unsigned char*)"jnodot", 106},
	{(const unsigned char*)"colone", 8788},
	{(const unsigned char*)"Eacgr", 904},
	{(const unsigned char*)"blk34", 9619},
	{(const unsigned char*)"eacgr", 941},
	{(const unsigned char*)"LongLeftArrow", 10229},
	{(const unsigned char*)"lE", 8806},
	{(const unsigned char*)"nsmid", 8740},
	{(const unsigned char*)"uacgr", 973},
	{(const unsigned char*)"boxVR", 9568},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Oacgr", 908},
	{(const unsigned char*)"aacgr", 940},
	{(const unsigned char*)"oacgr", 972},
	{(const unsigned char*)"luruhar", 10598},
	{(const unsigned char*)"ii", 8520},
	{NULL, 0},
	{(const unsigned char*)"telrec", 8981},
	{NULL, 0},
	{(const unsigned char*)"DDotrahd", 10513},
	{(const unsigned char*)"nle", 8816},
	{(const unsigned char*)"gtrless", 8823},
	{NULL, 0},
	{(const unsigned char*)"midcir", 10992},
	{(const unsigned char*)"DownArrowBar", 10515},
	{NULL, 0},
	{(const unsigned char*)"semi", 59},
	{(const unsigned char*)"Uacgr", 910},
	{(const unsigned char*)"lbrace", 123},
	{(const unsigned char*)"phmmat", 8499},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"rbrace", 125},
	{(const unsigned char*)"NotCongruent", 8802},
	{NULL, 0},
	{(const unsigned char*)"shchcy", 1097},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"simdot", 10858},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"cirmid", 10991},
	{NULL, 0},
	{(const unsigned char*)"SubsetEqual", 8838},
	{(const unsigned char*)"female", 9792},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"nsc", 8833},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"boxVH", 9580},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"ldrushar", 10571},
	{(const unsigned char*)"triangleright", 9657},
	{(const unsigned char*)"gneqq", 8809},
	{NULL, 0},
	{(const unsigned char*)"DownArrow", 8595},
	{NULL, 0},
	{(const unsigned char*)"backsim", 8765},
	{(const unsigned char*)"lneqq", 8808},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Sum", 8721},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"fflig", 64256},
	{NULL, 0},
	{(const unsigned char*)"hardcy", 1098},
	{(const unsigned char*)"nsub", 8836},
	{NULL, 0},
	{(const unsigned char*)"napprox", 8777},
	{(const unsigned char*)"caret", 8257},
	{NULL, 0},
	{(const unsigned char*)"succneqq", 10934},
	{(const unsigned char*)"frac13", 8531},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"num", 35},
	{(const unsigned char*)"emsp14", 8197},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"sum", 8721},
	{NULL, 0},
	{(const unsigned char*)"Cconint", 8752},
	{NULL, 0},
	{(const unsigned char*)"blacktriangleright", 9656},
	{NULL, 0},
	{(const unsigned char*)"SupersetEqual", 8839},
	{(const unsigned char*)"sim", 8764},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"LeftFloor", 8970},
	{NULL, 0},
	{(const unsigned char*)"RightTriangleEqual", 8885},
	{NULL, 0},
	{(const unsigned char*)"boxDr", 9555},
	{NULL, 0},
	{(const unsigned char*)"plus", 43},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"phiv", 966},
	{NULL, 0},
	{(const unsigned char*)"npr", 8832},
	{(const unsigned char*)"RightCeiling", 8969},
	{(const unsigned char*)"phone", 9742},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"mnplus", 8723},
	{NULL, 0},
	{(const unsigned char*)"vDash", 8872},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"isindot", 8949},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"PSgr", 936},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"ntriangleleft", 8938},
	{(const unsigned char*)"image", 8465},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"boxh", 9472},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"RightDownVector", 8642},
	{(const unsigned char*)"scpolint", 10771},
	{(const unsigned char*)"boxdL", 9557},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"RightUpTeeVector", 10588},
	{NULL, 0},
	{(const unsigned char*)"TSHcy", 1035},
	{(const unsigned char*)"longmapsto", 10236},
	{(const unsigned char*)"doublebarwedge", 8966},
	{(const unsigned char*)"frasl", 8260},
	{NULL, 0},
	{(const unsigned char*)"DoubleLongRightArrow", 10233},
	{(const unsigned char*)"gnE", 8809},
	{NULL, 0},
	{(const unsigned char*)"lnE", 8808},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"exponentiale", 8519},
	{NULL, 0},
	{(const unsigned char*)"larrfs", 10525},
	{(const unsigned char*)"NotDoubleVerticalBar", 8742},
	{NULL, 0},
	{(const unsigned char*)"curlywedge", 8911},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"rarrfs", 10526},
	{(const unsigned char*)"quatint", 10774},
	{NULL, 0},
	{(const unsigned char*)"frac58", 8541},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"gtreqless", 8923},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"PrecedesSlantEqual", 8828},
	{NULL, 0},
	{(const unsigned char*)"DotEqual", 8784},
	{(const unsigned char*)"iquest", 191},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"NotEqual", 8800},
	{NULL, 0},
	{(const unsigned char*)"barwedge", 8965},
	{(const unsigned char*)"b.gammad", 989},
	{NULL, 0},
	{(const unsigned char*)"block", 9608},
	{NULL, 0},
	{(const unsigned char*)"strns", 175},
	{NULL, 0},
	{(const unsigned char*)"prod", 8719},
	{(const unsigned char*)"cupre", 8828},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"SquareUnion", 8852},
	{(const unsigned char*)"Auml", 196},
	{NULL, 0},
	{(const unsigned char*)"upuparrows", 8648},
	{NULL, 0},
	{(const unsigned char*)"Euml", 203},
	{(const unsigned char*)"HorizontalLine", 9472},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Iuml", 207},
	{(const unsigned char*)"nvrArr", 10499},
	{(const unsigned char*)"bullet", 8226},
	{(const unsigned char*)"ClockwiseContourIntegral", 8754},
	{NULL, 0},
	{(const unsigned char*)"prop", 8733},
	{(const unsigned char*)"Ouml", 214},
	{NULL, 0},
	{(const unsigned char*)"chcy", 1095},
	{(const unsigned char*)"quaternions", 8461},
	{(const unsigned char*)"beth", 8502},
	{(const unsigned char*)"macr", 175},
	{(const unsigned char*)"Uuml", 220},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"khcy", 1093},
	{(const unsigned char*)"Star", 8902},
	{(const unsigned char*)"copysr", 8471},
	{(const unsigned char*)"Yuml", 376},
	{NULL, 0},
	{(const unsigned char*)"curren", 164},
	{NULL, 0},
	{(const unsigned char*)"Square", 9633},
	{(const unsigned char*)"shcy", 1096},
	{(const unsigned char*)"auml", 228},
	{NULL, 0},
	{(const unsigned char*)"boxUR", 9562},
	{(const unsigned char*)"uml", 168},
	{(const unsigned char*)"euml", 235},
	{NULL, 0},
	{(const unsigned char*)"zhcy", 1078},
	{(const unsigned char*)"iuml", 239},
	{NULL, 0},
	{(const unsigned char*)"Backslash", 8726},
	{(const unsigned char*)"square", 9633},
	{NULL, 0},
	{(const unsigned char*)"sqsube", 8849},
	{(const unsigned char*)"ouml", 246},
	{NULL, 0},
	{(const unsigned char*)"Tilde", 8764},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"prap", 10935},
	{(const unsigned char*)"uuml", 252},
	{(const unsigned char*)"cire", 8791},
	{NULL, 0},
	{(const unsigned char*)"dzigrarr", 10239},
	{(const unsigned char*)"yuml", 255},
	{(const unsigned char*)"star", 9734},
	{(const unsigned char*)"sqsubseteq", 8849},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"fork", 8916},
	{(const unsigned char*)"supsetneqq", 10956},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"DoubleDownArrow", 8659},
	{NULL, 0},
	{(const unsigned char*)"dharr", 8642},
	{(const unsigned char*)"lagran", 8466},
	{NULL, 0},
	{(const unsigned char*)"lrhard", 10605},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"downharpoonleft", 8643},
	{(const unsigned char*)"tilde", 732},
	{(const unsigned char*)"nharr", 8622},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"puncsp", 8200},
	{(const unsigned char*)"uharr", 8638},
	{(const unsigned char*)"boxHu", 9575},
	{(const unsigned char*)"models", 8871},
	{(const unsigned char*)"xharr", 10231},
	{(const unsigned char*)"nparallel", 8742},
	{NULL, 0},
	{(const unsigned char*)"Proportional", 8733},
	{NULL, 0},
	{(const unsigned char*)"ltrif", 9666},
	{NULL, 0},
	{(const unsigned char*)"dtrif", 9662},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"subsetneqq", 10955},
	{(const unsigned char*)"NotGreaterEqual", 8817},
	{(const unsigned char*)"rtrif", 9656},
	{NULL, 0},
	{(const unsigned char*)"utrif", 9652},
	{(const unsigned char*)"boxvl", 9508},
	{(const unsigned char*)"curvearrowleft", 8630},
	{(const unsigned char*)"lessapprox", 10885},
	{(const unsigned char*)"scnE", 10934},
	{(const unsigned char*)"thetasym", 977},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"ExponentialE", 8519},
	{(const unsigned char*)"andv", 10842},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"mapstodown", 8615},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"DownLeftVector", 8637},
	{(const unsigned char*)"rightharpoonup", 8640},
	{(const unsigned char*)"mapsto", 8614},
	{(const unsigned char*)"Lang", 12298},
	{(const unsigned char*)"SquareSuperset", 8848},
	{(const unsigned char*)"rightsquigarrow", 8605},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Rang", 12299},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"sigmav", 962},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"SquareIntersection", 8851},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"downharpoonright", 8642},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"lang", 9001},
	{(const unsigned char*)"compfn", 8728},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"rang", 9002},
	{NULL, 0},
	{(const unsigned char*)"Leftrightarrow", 8660},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"ReverseEquilibrium", 8651},
	{NULL, 0},
	{(const unsigned char*)"Rightarrow", 8658},
	{(const unsigned char*)"planck", 8463},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"KHgr", 935},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"OHgr", 937},
	{(const unsigned char*)"PHgr", 934},
	{NULL, 0},
	{(const unsigned char*)"sqsup", 8848},
	{NULL, 0},
	{(const unsigned char*)"THgr", 920},
	{NULL, 0},
	{(const unsigned char*)"rppolint", 10770},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"gtrapprox", 10886},
	{(const unsigned char*)"LongLeftRightArrow", 10231},
	{NULL, 0},
	{(const unsigned char*)"iinfin", 10716},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"frac16", 8537},
	{NULL, 0},
	{(const unsigned char*)"leftrightarrow", 8596},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"rightarrow", 8594},
	{(const unsigned char*)"risingdotseq", 8787},
	{NULL, 0},
	{(const unsigned char*)"blacksquare", 9642},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"DotDot", 8412},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"radic", 8730},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"nRightarrow", 8655},
	{NULL, 0},
	{(const unsigned char*)"reals", 8477},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"varphi", 966},
	{NULL, 0},
	{(const unsigned char*)"DownRightVector", 8641},
	{(const unsigned char*)"Equal", 10869},
	{(const unsigned char*)"NotCupCap", 8813},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"SucceedsTilde", 8831},
	{NULL, 0},
	{(const unsigned char*)"Succeeds", 8827},
	{(const unsigned char*)"dotplus", 8724},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"notniva", 8716},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"looparrowright", 8620},
	{(const unsigned char*)"ggg", 8921},
	{(const unsigned char*)"EmptySmallSquare", 9723},
	{NULL, 0},
	{(const unsigned char*)"nrtri", 8939},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"oS", 9416},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"IEcy", 1045},
	{NULL, 0},
	{(const unsigned char*)"succeq", 10928},
	{(const unsigned char*)"vrtri", 8883},
	{(const unsigned char*)"DownTeeArrow", 8615},
	{NULL, 0},
	{(const unsigned char*)"frac45", 8536},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"dblac", 733},
	{NULL, 0},
	{(const unsigned char*)"blk14", 9617},
	{NULL, 0},
	{(const unsigned char*)"lesseqqgtr", 10891},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"yucy", 1102},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"yicy", 1111},
	{NULL, 0},
	{(const unsigned char*)"gne", 10888},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"udhar", 10606},
	{(const unsigned char*)"UnionPlus", 8846},
	{(const unsigned char*)"blank", 9251},
	{(const unsigned char*)"lne", 10887},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"NotTildeFullEqual", 8775},
	{(const unsigned char*)"supE", 10950},
	{NULL, 0},
	{(const unsigned char*)"PlusMinus", 177},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"GreaterTilde", 8819},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"duarr", 8693},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"LeftDoubleBracket", 12314},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"CounterClockwiseContourIntegral", 8755},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"natural", 9838},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"uuarr", 8648},
	{(const unsigned char*)"biguplus", 10756},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"DownLeftVectorBar", 10582},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"subE", 10949},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"part", 8706},
	{(const unsigned char*)"drcorn", 8991},
	{(const unsigned char*)"horbar", 8213},
	{(const unsigned char*)"sbsol", 65128},
	{(const unsigned char*)"varrho", 1009},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"cudarrl", 10552},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"boxul", 9496},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"ordm", 186},
	{NULL, 0},
	{(const unsigned char*)"urcorn", 8989},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"dotminus", 8760},
	{(const unsigned char*)"scnsim", 8937},
	{(const unsigned char*)"andslope", 10840},
	{(const unsigned char*)"Cfr", 8493},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"rightthreetimes", 8908},
	{(const unsigned char*)"Hfr", 8460},
	{(const unsigned char*)"sqsubset", 8847},
	{(const unsigned char*)"lAtail", 10523},
	{(const unsigned char*)"rightleftharpoons", 8652},
	{(const unsigned char*)"Ifr", 8465},
	{(const unsigned char*)"infintie", 10717},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"rAtail", 10524},
	{(const unsigned char*)"scnap", 10938},
	{(const unsigned char*)"lharul", 10602},
	{(const unsigned char*)"Rfr", 8476},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"parallel", 8741},
	{(const unsigned char*)"rharul", 10604},
	{NULL, 0},
	{(const unsigned char*)"Zfr", 8488},
	{(const unsigned char*)"RuleDelayed", 10740},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"RightArrowLeftArrow", 8644},
	{(const unsigned char*)"profsurf", 8979},
	{(const unsigned char*)"nsupseteq", 8841},
	{(const unsigned char*)"nearhk", 10532},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"triangledown", 9663},
	{NULL, 0},
	{(const unsigned char*)"searhk", 10533},
	{(const unsigned char*)"empty", 8709},
	{NULL, 0},
	{(const unsigned char*)"DoubleUpArrow", 8657},
	{(const unsigned char*)"checkmark", 10003},
	{NULL, 0},
	{(const unsigned char*)"succapprox", 10936},
	{NULL, 0},
	{(const unsigned char*)"Cap", 8914},
	{(const unsigned char*)"RightTriangle", 8883},
	{NULL, 0},
	{(const unsigned char*)"tosa", 10537},
	{(const unsigned char*)"RightUpVector", 8638},
	{NULL, 0},
	{(const unsigned char*)"boxVL", 9571},
	{(const unsigned char*)"ecolon", 8789},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"Map", 10501},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"lbrack", 91},
	{(const unsigned char*)"THORN", 222},
	{(const unsigned char*)"DownArrowUpArrow", 8693},
	{NULL, 0},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"rbrack", 93},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"DiacriticalTilde", 732},
	{(const unsigned char*)"amp", 38},
	{(const unsigned char*)"rlhar2", 8652},
	{NULL, 0},
	{(const unsigned char*)"bcong", 8780},
	{NULL, 0},
	{NULL, 0},
	{(const unsigned char*)"exist", 8707},
	{(const unsigned char*)"ord", 10845},
	{NULL, 0},
	{(const unsigned char*)"cap", 8745},
	{(const unsigned char*)"eeacgr", 942},
	{(const unsigned char*)"PrecedesTilde", 8830},
	{(const unsigned char*)"divideontimes", 8903},
	{(const unsigned char*)"Precedes", 8826},
};
const struct hashtable entities_htable = {
	entities_htable_elements, 3079, 1643, 2463
};
